# docker/operator/Dockerfile

FROM python:3.10.14-slim

# Set the working directory
WORKDIR /app

# Copy the src directory
COPY ../src /app/src

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Set environment variables
ENV PYTHONPATH=/app/src

# Command to run the operator
CMD ["python", "/app/src/your_script.py"]